### ISSUE TITLE
bootstrap error: missing README

### ISSUE THREAD

**Issue by tsieger** [ggobi/ggobi#1]
Hi, this is a friendly notice that `./boostrap` fails with:
```
Makefile.am: error: required file './README' not found
doc/Makefile.am:8: warning: '%'-style pattern rules are a GNU make extension
src/Makefile.am:47: warning: '%'-style pattern rules are a GNU make extension
src/Makefile.am:55: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
src/Makefile.am: installing 'config/depcomp'
autoreconf: automake failed with exit status: 1
Copying file config/mkinstalldirs
```
Copying `README.md` to `README` apparently solves the issue.

BTW what is the current of ggobi? This version 2.1.4 seems to be obsoleted, since rggobi requires version 2.1.6. 
Also, http://ggobi.org/rggobi.html refers to 2.1.8 sources, but the link is not working.
Finally, I found sources to 2.1.11 at http://ggobi.org/downloads/.

**Comment by lawremi** [comment]
The bootstrap script should now do the copying, thanks for reporting. 

The current version is 2.1.12, which is somewhat confusingly on the ggobi-2.1.4 branch (we probably should have called it ggobi-2.1.x or something).
